[package]
name = "coffee"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6"
reqwest = "0.12.22"
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.46.1", features = ["full"] }
